import {ConfigBase, IElementBase} from "./ConfigBase";
import {AccessoriesGlovesConfig} from "./AccessoriesGloves";
import {AccountStageConfig} from "./AccountStage";
import {ActionConfigConfig} from "./ActionConfig";
import {ActionPropConfig} from "./ActionProp";
import {AIDataConfig} from "./AIData";
import {AIWayPointConfig} from "./AIWayPoint";
import {ALongCoatTopConfig} from "./ALongCoatTop";
import {AncientMoldingOutfitConfig} from "./AncientMoldingOutfit";
import {AssetsConfig} from "./Assets";
import {BackHairConfig} from "./BackHair";
import {BackConfig} from "./Back";
import {BlushConfig} from "./Blush";
import {BodyTypeConfig} from "./BodyType";
import {BootsShoesConfig} from "./BootsShoes";
import {BottomConfig} from "./Bottom";
import {BuffConfig} from "./Buff";
import {ChatConfig} from "./Chat";
import {CoinsGenerateConfig} from "./CoinsGenerate";
import {ColorValueConfig} from "./ColorValue";
import {ColorConfig} from "./Color";
import {DailyStylingOutfit1Config} from "./DailyStylingOutfit1";
import {DailyStylingOutfit2Config} from "./DailyStylingOutfit2";
import {DoorConfig} from "./Door";
import {EarConfig} from "./Ear";
import {EffectsConfig} from "./Effects";
import {EverydayShoesConfig} from "./EverydayShoes";
import {ExchangeConfig} from "./Exchange";
import {ExpressionConfig} from "./Expression";
import {expRuleConfig} from "./expRule";
import {EyebrowsConfig} from "./Eyebrows";
import {EyelashesConfig} from "./Eyelashes";
import {EyeshadowConfig} from "./Eyeshadow";
import {FaceExpressionConfig} from "./FaceExpression";
import {FaceTattooConfig} from "./FaceTattoo";
import {FaceConfig} from "./Face";
import {FacingConfig} from "./Facing";
import {FantasyModelingOutfitConfig} from "./FantasyModelingOutfit";
import {FootCoverShoesConfig} from "./FootCoverShoes";
import {FrontHairConfig} from "./FrontHair";
import {FullHairConfig} from "./FullHair";
import {GlovesGlovesConfig} from "./GlovesGloves";
import {GlovesConfig} from "./Gloves";
import {GuideConfig} from "./Guide";
import {HeroStylingOutfitConfig} from "./HeroStylingOutfit";
import {HighHeelsShoesConfig} from "./HighHeelsShoes";
import {HipConfig} from "./Hip";
import {HolidayStylingOutfitConfig} from "./HolidayStylingOutfit";
import {IdentityConfig} from "./Identity";
import {LanguageConfig} from "./Language";
import {LeftHandConfig} from "./LeftHand";
import {LensConfig} from "./Lens";
import {LevelConfig} from "./Level";
import {LipMakeupConfig} from "./LipMakeup";
import {LongPantsBottomConfig} from "./LongPantsBottom";
import {LongSinglePieceTopConfig} from "./LongSinglePieceTop";
import {LongSkirtBottomConfig} from "./LongSkirtBottom";
import {LotteryConfig} from "./Lottery";
import {LowerHighlightConfig} from "./LowerHighlight";
import {MemberConfig} from "./Member";
import {MuppetStylingOutfitConfig} from "./MuppetStylingOutfit";
import {NakedDressShoesConfig} from "./NakedDressShoes";
import {OutfitConfig} from "./Outfit";
import {PetConfig} from "./Pet";
import {PropsGenerateConfig} from "./PropsGenerate";
import {PupilStyleConfig} from "./PupilStyle";
import {RankConfig} from "./Rank";
import {RightHandConfig} from "./RightHand";
import {RoleConfig} from "./Role";
import {RuleConfig} from "./Rule";
import {SceneItemConfig} from "./SceneItem";
import {ScienceFictionStylingOutfitConfig} from "./ScienceFictionStylingOutfit";
import {ShoesConfig} from "./Shoes";
import {ShopConfig} from "./Shop";
import {ShortJacketTopConfig} from "./ShortJacketTop";
import {ShortsBottomConfig} from "./ShortsBottom";
import {ShortSinglePieceTopConfig} from "./ShortSinglePieceTop";
import {ShortSkirtBottomConfig} from "./ShortSkirtBottom";
import {ShoulderConfig} from "./Shoulder";
import {SkillShopConfig} from "./SkillShop";
import {SkillConfig} from "./Skill";
import {SkinToneConfig} from "./SkinTone";
import {SoundConfig} from "./Sound";
import {SportsShoesShoesConfig} from "./SportsShoesShoes";
import {SuitTopConfig} from "./SuitTop";
import {Tab1Config} from "./Tab1";
import {Tab2Config} from "./Tab2";
import {Tab3Config} from "./Tab3";
import {TextConfig} from "./Text";
import {TightsBottomConfig} from "./TightsBottom";
import {TipsConfig} from "./Tips";
import {TopConfig} from "./Top";
import {TrailingConfig} from "./Trailing";
import {UpperHighlightConfig} from "./UpperHighlight";
import {WeaponConfig} from "./Weapon";

export class GameConfig{
	private static configMap:Map<string, ConfigBase<IElementBase>> = new Map();
	/**
	* 多语言设置
	* @param languageIndex 语言索引(-1为系统默认语言)
	* @param getLanguageFun 根据key获取语言内容的方法
	*/
	public static initLanguage(languageIndex:number, getLanguageFun:(key:string|number)=>string){
		ConfigBase.initLanguage(languageIndex, getLanguageFun);
		this.configMap.clear();
	}
	public static getConfig<T extends ConfigBase<IElementBase>>(ConfigClass: { new(): T }): T {
		if (!this.configMap.has(ConfigClass.name)) {
			this.configMap.set(ConfigClass.name, new ConfigClass());
		}
		return this.configMap.get(ConfigClass.name) as T;
	}
	public static get AccessoriesGloves():AccessoriesGlovesConfig{ return this.getConfig(AccessoriesGlovesConfig) };
	public static get AccountStage():AccountStageConfig{ return this.getConfig(AccountStageConfig) };
	public static get ActionConfig():ActionConfigConfig{ return this.getConfig(ActionConfigConfig) };
	public static get ActionProp():ActionPropConfig{ return this.getConfig(ActionPropConfig) };
	public static get AIData():AIDataConfig{ return this.getConfig(AIDataConfig) };
	public static get AIWayPoint():AIWayPointConfig{ return this.getConfig(AIWayPointConfig) };
	public static get ALongCoatTop():ALongCoatTopConfig{ return this.getConfig(ALongCoatTopConfig) };
	public static get AncientMoldingOutfit():AncientMoldingOutfitConfig{ return this.getConfig(AncientMoldingOutfitConfig) };
	public static get Assets():AssetsConfig{ return this.getConfig(AssetsConfig) };
	public static get BackHair():BackHairConfig{ return this.getConfig(BackHairConfig) };
	public static get Back():BackConfig{ return this.getConfig(BackConfig) };
	public static get Blush():BlushConfig{ return this.getConfig(BlushConfig) };
	public static get BodyType():BodyTypeConfig{ return this.getConfig(BodyTypeConfig) };
	public static get BootsShoes():BootsShoesConfig{ return this.getConfig(BootsShoesConfig) };
	public static get Bottom():BottomConfig{ return this.getConfig(BottomConfig) };
	public static get Buff():BuffConfig{ return this.getConfig(BuffConfig) };
	public static get Chat():ChatConfig{ return this.getConfig(ChatConfig) };
	public static get CoinsGenerate():CoinsGenerateConfig{ return this.getConfig(CoinsGenerateConfig) };
	public static get ColorValue():ColorValueConfig{ return this.getConfig(ColorValueConfig) };
	public static get Color():ColorConfig{ return this.getConfig(ColorConfig) };
	public static get DailyStylingOutfit1():DailyStylingOutfit1Config{ return this.getConfig(DailyStylingOutfit1Config) };
	public static get DailyStylingOutfit2():DailyStylingOutfit2Config{ return this.getConfig(DailyStylingOutfit2Config) };
	public static get Door():DoorConfig{ return this.getConfig(DoorConfig) };
	public static get Ear():EarConfig{ return this.getConfig(EarConfig) };
	public static get Effects():EffectsConfig{ return this.getConfig(EffectsConfig) };
	public static get EverydayShoes():EverydayShoesConfig{ return this.getConfig(EverydayShoesConfig) };
	public static get Exchange():ExchangeConfig{ return this.getConfig(ExchangeConfig) };
	public static get Expression():ExpressionConfig{ return this.getConfig(ExpressionConfig) };
	public static get expRule():expRuleConfig{ return this.getConfig(expRuleConfig) };
	public static get Eyebrows():EyebrowsConfig{ return this.getConfig(EyebrowsConfig) };
	public static get Eyelashes():EyelashesConfig{ return this.getConfig(EyelashesConfig) };
	public static get Eyeshadow():EyeshadowConfig{ return this.getConfig(EyeshadowConfig) };
	public static get FaceExpression():FaceExpressionConfig{ return this.getConfig(FaceExpressionConfig) };
	public static get FaceTattoo():FaceTattooConfig{ return this.getConfig(FaceTattooConfig) };
	public static get Face():FaceConfig{ return this.getConfig(FaceConfig) };
	public static get Facing():FacingConfig{ return this.getConfig(FacingConfig) };
	public static get FantasyModelingOutfit():FantasyModelingOutfitConfig{ return this.getConfig(FantasyModelingOutfitConfig) };
	public static get FootCoverShoes():FootCoverShoesConfig{ return this.getConfig(FootCoverShoesConfig) };
	public static get FrontHair():FrontHairConfig{ return this.getConfig(FrontHairConfig) };
	public static get FullHair():FullHairConfig{ return this.getConfig(FullHairConfig) };
	public static get GlovesGloves():GlovesGlovesConfig{ return this.getConfig(GlovesGlovesConfig) };
	public static get Gloves():GlovesConfig{ return this.getConfig(GlovesConfig) };
	public static get Guide():GuideConfig{ return this.getConfig(GuideConfig) };
	public static get HeroStylingOutfit():HeroStylingOutfitConfig{ return this.getConfig(HeroStylingOutfitConfig) };
	public static get HighHeelsShoes():HighHeelsShoesConfig{ return this.getConfig(HighHeelsShoesConfig) };
	public static get Hip():HipConfig{ return this.getConfig(HipConfig) };
	public static get HolidayStylingOutfit():HolidayStylingOutfitConfig{ return this.getConfig(HolidayStylingOutfitConfig) };
	public static get Identity():IdentityConfig{ return this.getConfig(IdentityConfig) };
	public static get Language():LanguageConfig{ return this.getConfig(LanguageConfig) };
	public static get LeftHand():LeftHandConfig{ return this.getConfig(LeftHandConfig) };
	public static get Lens():LensConfig{ return this.getConfig(LensConfig) };
	public static get Level():LevelConfig{ return this.getConfig(LevelConfig) };
	public static get LipMakeup():LipMakeupConfig{ return this.getConfig(LipMakeupConfig) };
	public static get LongPantsBottom():LongPantsBottomConfig{ return this.getConfig(LongPantsBottomConfig) };
	public static get LongSinglePieceTop():LongSinglePieceTopConfig{ return this.getConfig(LongSinglePieceTopConfig) };
	public static get LongSkirtBottom():LongSkirtBottomConfig{ return this.getConfig(LongSkirtBottomConfig) };
	public static get Lottery():LotteryConfig{ return this.getConfig(LotteryConfig) };
	public static get LowerHighlight():LowerHighlightConfig{ return this.getConfig(LowerHighlightConfig) };
	public static get Member():MemberConfig{ return this.getConfig(MemberConfig) };
	public static get MuppetStylingOutfit():MuppetStylingOutfitConfig{ return this.getConfig(MuppetStylingOutfitConfig) };
	public static get NakedDressShoes():NakedDressShoesConfig{ return this.getConfig(NakedDressShoesConfig) };
	public static get Outfit():OutfitConfig{ return this.getConfig(OutfitConfig) };
	public static get Pet():PetConfig{ return this.getConfig(PetConfig) };
	public static get PropsGenerate():PropsGenerateConfig{ return this.getConfig(PropsGenerateConfig) };
	public static get PupilStyle():PupilStyleConfig{ return this.getConfig(PupilStyleConfig) };
	public static get Rank():RankConfig{ return this.getConfig(RankConfig) };
	public static get RightHand():RightHandConfig{ return this.getConfig(RightHandConfig) };
	public static get Role():RoleConfig{ return this.getConfig(RoleConfig) };
	public static get Rule():RuleConfig{ return this.getConfig(RuleConfig) };
	public static get SceneItem():SceneItemConfig{ return this.getConfig(SceneItemConfig) };
	public static get ScienceFictionStylingOutfit():ScienceFictionStylingOutfitConfig{ return this.getConfig(ScienceFictionStylingOutfitConfig) };
	public static get Shoes():ShoesConfig{ return this.getConfig(ShoesConfig) };
	public static get Shop():ShopConfig{ return this.getConfig(ShopConfig) };
	public static get ShortJacketTop():ShortJacketTopConfig{ return this.getConfig(ShortJacketTopConfig) };
	public static get ShortsBottom():ShortsBottomConfig{ return this.getConfig(ShortsBottomConfig) };
	public static get ShortSinglePieceTop():ShortSinglePieceTopConfig{ return this.getConfig(ShortSinglePieceTopConfig) };
	public static get ShortSkirtBottom():ShortSkirtBottomConfig{ return this.getConfig(ShortSkirtBottomConfig) };
	public static get Shoulder():ShoulderConfig{ return this.getConfig(ShoulderConfig) };
	public static get SkillShop():SkillShopConfig{ return this.getConfig(SkillShopConfig) };
	public static get Skill():SkillConfig{ return this.getConfig(SkillConfig) };
	public static get SkinTone():SkinToneConfig{ return this.getConfig(SkinToneConfig) };
	public static get Sound():SoundConfig{ return this.getConfig(SoundConfig) };
	public static get SportsShoesShoes():SportsShoesShoesConfig{ return this.getConfig(SportsShoesShoesConfig) };
	public static get SuitTop():SuitTopConfig{ return this.getConfig(SuitTopConfig) };
	public static get Tab1():Tab1Config{ return this.getConfig(Tab1Config) };
	public static get Tab2():Tab2Config{ return this.getConfig(Tab2Config) };
	public static get Tab3():Tab3Config{ return this.getConfig(Tab3Config) };
	public static get Text():TextConfig{ return this.getConfig(TextConfig) };
	public static get TightsBottom():TightsBottomConfig{ return this.getConfig(TightsBottomConfig) };
	public static get Tips():TipsConfig{ return this.getConfig(TipsConfig) };
	public static get Top():TopConfig{ return this.getConfig(TopConfig) };
	public static get Trailing():TrailingConfig{ return this.getConfig(TrailingConfig) };
	public static get UpperHighlight():UpperHighlightConfig{ return this.getConfig(UpperHighlightConfig) };
	public static get Weapon():WeaponConfig{ return this.getConfig(WeaponConfig) };
}